version: "3.9"

services:
  db:
    image: postgres:16
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: taskmanager-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskmanager
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=secret123
    command: [ "sh", "-c", "sleep 10 && java -jar app.jar" ]  # dodatkowy bufor 10s
    restart: on-failure:5
volumes:
  pgdata:
